<?php
/**
 * This file is part of the Imbo package
 *
 * (c) Christer Edvartsen <cogo@starzinger.net>
 *
 * For the full copyright and license information, please view the LICENSE file that was
 * distributed with this source code.
 */

use ImboBehatFeatureContext\FeatureContext;
use Imbo\Auth\AccessControl\Adapter\ArrayAdapter;
use Imbo\Resource;

// Default Imbo config. This is loaded early as the config.default.php class loads the autoloader
// generated by Composer, which also enables the loading of the Behat feature context class that is
// referred to in the X-Behat-Context-Class request header
$defaultConfig = require __DIR__ . '/../../../config/config.default.php';

if (empty($_SERVER['HTTP_X_BEHAT_CONTEXT_CLASS'])) {
    throw new RuntimeException('Missing X-Behat-Context-Class request header');
}

$contextClass = $_SERVER['HTTP_X_BEHAT_CONTEXT_CLASS'];

if (!class_exists($contextClass)) {
    throw new RuntimeException(sprintf(
        'Specified Behat feature context class does not exist: "%s"',
        $contextClass
    ));
} else if (($interfaces = class_implements($contextClass)) === false || !in_array(FeatureContext::class, $interfaces)) {
    throw new RuntimeException(sprintf(
        'The "%s" class must implement the "%s" interface',
        $contextClass,
        FeatureContext::class
    ));
}

// Default config for testing
$testConfig = [
    'accessControl' => function() {
        return new ArrayAdapter([
            [
                'publicKey' => 'publicKey',
                'privateKey' => 'privateKey',
                'acl' => [[
                    'resources' => Resource::getReadWriteResources(),
                    'users' => ['user', 'other-user'],
                ]]
            ],
            [
                'publicKey' => 'unpriviledged',
                'privateKey' => 'privateKey',
                'acl' => [[
                    'resources' => Resource::getReadWriteResources(),
                    'users' => ['user'],
                ]]
            ],
            [
                'publicKey' => 'wildcard',
                'privateKey' => '*',
                'acl' => [[
                    'resources' => Resource::getReadWriteResources(),
                    'users' => '*'
                ]]
            ]
        ]);
    },

    'database' => $contextClass::getDatabaseAdapter(),
    'storage' => $contextClass::getStorageAdapter(),
];

// Custom test config, if any, specified in the X-Imbo-Test-Config-File HTTP request header
$customConfig = [];

if (isset($_SERVER['HTTP_X_IMBO_TEST_CONFIG_FILE'])) {
    $customConfig = require __DIR__ . '/' . basename($_SERVER['HTTP_X_IMBO_TEST_CONFIG_FILE']);
}

// Return the merged configuration, having the custom config overwrite the default testing config,
// which in turn overwrites the default config
return array_replace_recursive($defaultConfig, $testConfig, $customConfig);
